### PR TITLE
WIP: Add ratio estimator selection

### PR DESCRIPTION
**Pull request by Sinclert**
**~[This is a Work in Progress. Do not merge]~**

This PR addresses the desire to select a particular _ratio_ type Estimator, in order to perform comparisons between:

- The default `ParameterizedRatioEstimator` class.
- The new `QuadraticMorphingAwareRatioEstimator` class (introduced in [madminer 0.7.5](https://github.com/diana-hep/madminer/releases/tag/v0.7.5)).

In order to do so, a selector function is defined within the [shared](https://github.com/scailfin/madminer-workflow-ml/blob/3ec1a1a5a7224e10343db9c8edee9aa92a779f89/code/shared/ratio_estimators.py) Python module, so that both the _"train"_ and _"evaluation"_ Yadage steps can instantiate the same Estimator.

#### Additional changes:
- Version has been bumped to `0.2.1`.

#### Remaining tasks:
- ~When locally testing a Yadage execution (`make yadage-run`), a Madminer `0.7.5` bug is found. Debugging needed.~

### CODE REVIEW

**Comment by Sinclert** [comment]
Please. @irinaespejo , review commits:

- 8f333a2640527c63bc22d1886997eb9a9f46915d on what we referred to when talking about _bumping madminer version_.
- 7567280e88d1dc9814ebac7bf52e8ff2e74265a9 on how to define a better class selection function (instead of `if/else`).

**Comment by Sinclert** [comment]
The problem seem to be related with h5py `v3.0.0`. [Tracking issue](https://github.com/diana-hep/madminer/issues/446).

**Comment by Sinclert** [comment]
The [described issue](https://github.com/diana-hep/madminer/issues/446) has been solved on [Madminer `v0.7.6`](https://github.com/diana-hep/madminer/releases/tag/v0.7.6)

Merging PR.

**Comment by johannbrehmer** [comment]
Thanks Sinclert, this looks good!

**Pull request merged**
